In [9]:
import pandas as pd
import numpy as np

In [3]:
num_list = [1,2,3,4]
num_arr = np.array(num_list)
s = pd.Series(num_arr)


## np.arange()

In [12]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
a = range(12)
print(a)
print(list(a))

range(0, 12)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [13]:
a = np.arange(4,12,2)
a

array([ 4,  6,  8, 10])

## for문

In [29]:
for i in [1,2,3]:
    print(i)
    
for i in range(1,4):
    print('\t',i)
    
for i in np.arange(1,4):
    print(i)

1
2
3
	 1
	 2
	 3
1
2
3


In [30]:
for i in range(3):
    print(i)
    
for i in np.arange(3):
    print('\t',i)
    

0
1
2
	 0
	 1
	 2


# np.zeros(), np.ones() &  _like()

- zeros

In [35]:
np.zeros(5, dtype = int)
# np.zeros(5, dtype = object)

array([0, 0, 0, 0, 0])

In [37]:
np.zeros((5,5), dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [42]:
a = np.arange(5)
print(np.zeros_like(a))

[0 0 0 0 0]


----

- ones

In [36]:
np.ones(5, dtype = int)
# np.ones(5, dtype = object)

array([1, 1, 1, 1, 1])

In [39]:
np.ones((5,3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [43]:
a = np.arange(5)
print(np.ones_like(a))

[1 1 1 1 1]


---

# 차수 Dimension
<img src ='https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FcSoMOs%2Fbtqt0a2Dc2y%2FQhkfwhiWqeUKvNfsM2H29K%2Fimg.png
'>

## 1D
- axis 0

In [4]:
# np.ndim : 차원이 몇 차원이야?
print(np.ndim(num_list))
print(np.ndim(num_arr))
print(np.ndim(s))

1
1
1


## 2D
- axis 0, axis 1

In [11]:
num_2d = [[1,2,3,4]]
print(np.ndim(num_2d))

2


## 3D 
* (덩어리, 줄, 칸)
<pre>
<font color=red><b>axis=0 : (_____ 줄,칸)   세로(↓)
<font color=red><b>axis=1 : (덩어리,__,칸)  가로(→)
<font color=red><b>axis=2 : (덩어리,줄,__)  폭

In [51]:
one_3 =  np.ones((5,3,3))

print(one_3)
print(f'차원 수 : {np.ndim(one_3)}')

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
차원 수 : 3


# reshape()

In [56]:
num_arr = np.arange(0,24)
print(num_arr.shape, '\n', num_arr)

re_arr = num_arr.reshape(6,4)
print(re_arr.shape, '\n', re_arr)

re_arr = num_arr.reshape(2,12)
print(re_arr.shape, '\n', re_arr)

re_arr = num_arr.reshape(2,2,6)
print(re_arr.shape, '\n', re_arr)

(24,) 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(6, 4) 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
(2, 12) 
 [[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
(2, 2, 6) 
 [[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]]


## reshape() vs resize()
- <b>reshape()</b> : 원본에 복제를 함, 리턴이 있음
- <b>resize()</b>  : 원본을 바로 바꿔버림, 리턴이 없음

In [18]:
num_arr = np.arange(0,24)
re_arr = num_arr.reshape(6,4)

print(num_arr)
print(re_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [19]:
num_arr = np.arange(0,24)
re_arr = num_arr.resize(6,4)

print(num_arr)
print(re_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
None


# 차원 확대
- <b>reshape()
-  <b>슬라이싱 [:, np.newaxis or None]
-  <b>np.expand_dims(a,axis)

## reshape()


In [23]:
num_arr = np.arange(0,24)
print(num_arr.ndim, num_arr.shape,'\n', num_arr)

res = num_arr.reshape(1,-1)
print(res.ndim,res.shape, '\n', res)
# res = num_arr.reshape(1,24)
# print(res.ndim,,res.shape, '\n', res)

res = num_arr.reshape(-1,1)
print(res.ndim,res.shape, '\n', res)
# res = num_arr.reshape(24,1)
# print(res.ndim,,res.shape, '\n', res)

1 (24,) 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
2 (1, 24) 
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]
2 (24, 1) 
 [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [24]:
num_arr = np.arange(0,24)
print(num_arr.ndim, num_arr.shape,'\n', num_arr)

res = num_arr.reshape(2,3,4)
print(res.ndim,res.shape, '\n', res)

1 (24,) 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
3 (2, 3, 4) 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## 슬라이싱 [:, np.newaxis or None]

In [28]:
num_arr = np.arange(0,24)
print(num_arr.ndim, num_arr.shape,'\n', num_arr)

res = num_arr[np.newaxis,:]
print(res.ndim,res.shape, '\n', res)
# res = num_arr[None,:]
# print(res.ndim,res.shape, '\n', res)

res = num_arr[:, np.newaxis]
print(res.ndim,res.shape, '\n', res)
# res = num_arr[:, None]
# print(res.ndim,res.shape, '\n', res)

1 (24,) 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
2 (1, 24) 
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]
2 (24, 1) 
 [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


## np.expand_dims(a,axis)


In [35]:
num_arr = np.arange(0,24)
print(num_arr.ndim, num_arr.shape,'\n', num_arr)

res = np.expand_dims(num_arr, axis = 0)
print(res.ndim,res.shape, '\n', res)

res = np.expand_dims(num_arr, axis = 1)
print(res.ndim,res.shape, '\n', res[:2])

res = np.expand_dims(num_arr, axis = (1,2))
print(res.ndim,res.shape, '\n', res[:2])

res = np.expand_dims(num_arr, axis = (0,2))
print(res.ndim,res.shape, '\n', res[:2])

1 (24,) 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
2 (1, 24) 
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]
2 (24, 1) 
 [[0]
 [1]]
3 (24, 1, 1) 
 [[[0]]

 [[1]]]
3 (1, 24, 1) 
 [[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]
  [13]
  [14]
  [15]
  [16]
  [17]
  [18]
  [19]
  [20]
  [21]
  [22]
  [23]]]


# 차원 축소
- 1차원 : reshape(-1,) ravel() flatten()
- 슬라이싱 : 
- np.squeeze()

## reshape()
* reshape(행,열) : (행, -1) : 알아서 계산
* <font color=red><b>reshpae(-1) == ravel() == flatten() : 1차로 만들기

In [37]:
num_arr = np.arange(0,24)
print(num_arr)
# re_arr = num_arr.reshape(6,4) #6줄4칸
re_arr = num_arr.reshape(2,3,-1) #6줄 , 칸은 알아서 계산
print(re_arr)

aa = re_arr.reshape(-1) 
print(aa)

bb = re_arr.ravel() 
print(bb)

cc = re_arr.flatten()
print(cc)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


## 슬라이싱

In [39]:
num_arr = np.arange(0,24)
print(num_arr.ndim,num_arr.shape, '\n', num_arr )

re_arr = num_arr.reshape(6,4)
print(re_arr.ndim,re_arr.shape, '\n', re_arr )

res = re_arr[1,:]
print(res.ndim,res.shape, '\n', res )

res = re_arr[:,2]
print(res.ndim,res.shape, '\n', res )


1 (24,) 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
2 (6, 4) 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
1 (4,) 
 [4 5 6 7]
1 (6,) 
 [ 2  6 10 14 18 22]


In [40]:
num_arr = np.arange(0,24)
print(num_arr.ndim,num_arr.shape, '\n', num_arr )

re_arr = num_arr.reshape(2,3,4)
print(re_arr.ndim,re_arr.shape, '\n', re_arr )

res = re_arr[1,:]
print(res.ndim,res.shape, '\n', res )

res = re_arr[:,2]
print(res.ndim,res.shape, '\n', res )


1 (24,) 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
3 (2, 3, 4) 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
2 (3, 4) 
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
2 (2, 4) 
 [[ 8  9 10 11]
 [20 21 22 23]]


In [45]:
num_arr = np.arange(0,24)
re_arr = num_arr.reshape(2,3,4)
print(re_arr.ndim,re_arr.shape, '\n', re_arr )

res = re_arr[1,...]
print(res.ndim,res.shape, '\n', res )

3 (2, 3, 4) 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
2 (3, 4) 
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


## np.squeeze()
- 차수 1은 다 없앰

In [49]:
num_arr = np.arange(0,24)

re_arr = num_arr.reshape(1,24,1)
print(re_arr.ndim,re_arr.shape)

res = np.squeeze(re_arr,axis = None)
print(res.ndim,res.shape, '\n', res )


re_arr = num_arr.reshape(1,6,1,4,1)
print(re_arr.ndim,re_arr.shape)

res = np.squeeze(re_arr,axis = None)
print(res.ndim,res.shape, '\n', res )

3 (1, 24, 1)
1 (24,) 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
5 (1, 6, 1, 4, 1)
2 (6, 4) 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


# 축 (axis)

- axis = None : sum all of the elements

- np.sum
    - axis 0 를 무시
    - axis 1 를 무시
    - axis 2 를 무시

In [58]:
num_arr = np.arange(0,24)
print(num_arr)
np.sum(num_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


276

In [62]:
re_arr = num_arr.reshape(4,6)
print(re_arr)
print(f'axis =0 일때 합 : {np.sum(re_arr,axis=0)}')
print(f'axis =1 일때 합 : {np.sum(re_arr,axis=1)}')

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
axis =0 일때 합 : [36 40 44 48 52 56]
axis =1 일때 합 : [ 15  51  87 123]


In [72]:
re_arr = num_arr.reshape(2,3,4)
print(re_arr.shape)
print(re_arr,'\n')
print(f'axis =0 일때 합 (3*4):\n {np.sum(re_arr,axis=0)}\n')
print(f'axis =1 일때 합 (2*4):\n {np.sum(re_arr,axis=1)}\n')
print(f'axis =2 일때 합 (2*3): \n{np.sum(re_arr,axis=2)}\n')

(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 

axis =0 일때 합 (3*4):
 [[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

axis =1 일때 합 (2*4):
 [[12 15 18 21]
 [48 51 54 57]]

axis =2 일때 합 (2*3): 
[[ 6 22 38]
 [54 70 86]]



In [79]:
print(re_arr.reshape(-1))
print(np.ndim(re_arr.reshape(-1)))

print(re_arr.flatten())
print(np.ndim(re_arr.flatten()))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


# stack
- ref : https://rfriend.tistory.com/352

<img src = 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Ft1.daumcdn.net%2Fcfile%2Ftistory%2F9909EF345D53F4D916'>

In [95]:
a = np.arange(3)
b = np.arange(10,13)


print(np.hstack([a,b]))
print(np.vstack([a,b]))
# ========================
print('=====')
print(np.stack([a,b],axis=1))
print(np.stack([a,b],axis=0))
print('=====')
# ========================

print(np.column_stack([a.T,b.T]))
print(np.hstack([a.T,b.T]))
print(np.vstack([a.T,b.T]))

[ 0  1  2 10 11 12]
[[ 0  1  2]
 [10 11 12]]
=====
[[ 0 10]
 [ 1 11]
 [ 2 12]]
[[ 0  1  2]
 [10 11 12]]
=====
[[ 0 10]
 [ 1 11]
 [ 2 12]]
[ 0  1  2 10 11 12]
[[ 0  1  2]
 [10 11 12]]


# scalar , vector
<img src='https://art28.github.io/assets/lecture_asset/linear_algebra/1_1.png
'>

# 요소 접근

In [97]:
num_arr = np.arange(0,24)
re_arr = num_arr.reshape(2,3,4)
re_arr[0][0].shape

(4,)

# broadcasting
- ref : https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html


<img src = 'https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png'>

- <b>np에서 broadcasting</b> : 
    - 규칙 1: 두 배열의 차원 수가 다른 경우 차원이 더 적은 배열의 모양이 차원이 큰 모형과 같은 배열으로 채워집니다.
    - 규칙 2: 두 배열의 모양이 차원에서 일치하지 않으면 해당 차원에서 모양이 1인 배열이 다른 모양과 일치하도록 늘어납니다.
    - 규칙 3: 차원에서 크기가 일치하지 않고 둘 다 1이 아니면 오류가 발생합니다.
    
- np에서 사칙연산이 가능한 원리 -> 브로드캐스팅

In [4]:
num_list = [1,2,3]
# num_list += 3 # 에러
num_list *= 3   # 리스트를 반복해라
print(num_list)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


- 리스트에서 append와 extend

In [7]:
num_list = [1,2,3]
l = [1,2,3]
# num_list.append(l) # [1, 2, 3, [1, 2, 3]]
num_list.extend(l)   # [1, 2, 3, 1, 2, 3]
print(num_list)

[1, 2, 3, 1, 2, 3]


* np.array 에서 사칙연산

In [10]:
num_arr = np.arange(1,4)  #( 1  2  3 )
num_arr += 3 
print(num_arr)
num_arr *= 3  
print(num_arr)

[4 5 6]
[12 15 18]


In [17]:
num_arr = np.arange(1,4)  #( 1  2  3 )
l = [1,2,3]
v_s = np.vstack([num_arr,l])
h_s = np.hstack([num_arr,l])  
print(v_s)
print(h_s)

[[1 2 3]
 [1 2 3]]
[1 2 3 1 2 3]
